# Generated by Django 4.2.1 on 2023-06-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_pk', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('composedEmail', models.CharField(max_length=5000)),
            ],
        ),
    ]
